name: lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: lint
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Check formatting with black
      run: |
        pip install black
        black --check .
